fix: fix errors in internal/generate/golang
Fix these test failures:

--- FAIL: TestGolangCILint (1.78s)
    all_test.go:224: /Users/julieqiu/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.darwin-arm64/bin/go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.6.0 run: exit status 1
        internal/generate/golang/bazel/parser.go:68:1: Comment should end in a period (godot)
        // E.g., cloud.google.com/go/asset/apiv1;asset
        ^
        internal/generate/golang/bazel/parser.go:73:1: Comment should end in a period (godot)
        // E.g., googleapis/google/cloud/asset/v1/cloudasset_v1.yaml
        ^
        internal/generate/golang/build/builder.go:74:1: Comment should end in a period (godot)
        // goBuild builds all the code under the specified directory
        ^
        internal/generate/golang/generate/manifest.go:50:27: generateRepoMetadata - ctx is unused (unparam)
        func generateRepoMetadata(ctx context.Context, cfg *Config, lib *request.Library, api *request.API, moduleConfig *config.ModuleConfig, bazelConfig *bazel.Config) error {
                                  ^
        internal/generate/golang/generate/manifest.go:126:53: docURL - result 1 (error) is always nil (unparam)
        func docURL(modulePath, importPath string) (string, error) {
                                                            ^
        internal/generate/golang/generate/manifest.go:140:74: releaseLevel - result 1 (error) is always nil (unparam)
        func releaseLevel(importPath string, bazelConfig *bazel.Config) (string, error) {
                                                                                 ^
        internal/generate/golang/build/builder_test.go:127:17: os.MkdirTemp() could be replaced by t.TempDir() in newTestEnv (usetesting)
        	tmpDir, err := os.MkdirTemp("", "builder-test")
        	               ^
        internal/generate/golang/configure/configure_test.go:44:17: os.MkdirTemp() could be replaced by t.TempDir() in newTestEnv (usetesting)
        	tmpDir, err := os.MkdirTemp("", "configure-test")
        	               ^
        internal/generate/golang/generate/generator_test.go:39:17: os.MkdirTemp() could be replaced by t.TempDir() in newTestEnv (usetesting)
        	tmpDir, err := os.MkdirTemp("", "generator-test")
        	               ^
        internal/generate/golang/generate/generator_test.go:247:17: os.MkdirTemp() could be replaced by t.TempDir() in TestFixPermissions (usetesting)
        	tmpDir, err := os.MkdirTemp("", "permissions-test")
        	               ^
        internal/generate/golang/generate/generator_test.go:302:17: os.MkdirTemp() could be replaced by t.TempDir() in TestFlattenOutput (usetesting)
        	tmpDir, err := os.MkdirTemp("", "flatten-test")
        	               ^
        internal/generate/golang/generate/generator_test.go:447:19: os.MkdirTemp() could be replaced by t.TempDir() in TestApplyModuleVersion (usetesting)
        			tmpDir, err := os.MkdirTemp("", "apply-module-version-test")
        			               ^
        internal/generate/golang/generate/generator_test.go:478:17: os.MkdirTemp() could be replaced by t.TempDir() in TestDeleteOutputPaths (usetesting)
        	tmpDir, err := os.MkdirTemp("", "apply-module-version-test")
        	               ^
        13 issues:
        * godot: 3
        * unparam: 3
        * usetesting: 7
        exit status 1
--- FAIL: TestExportedSymbolsHaveDocs (0.02s)
    all_test.go:301: package request does not have package comment
    all_test.go:301: package generate does not have package comment
    all_test.go:301: package bazel does not have package comment
    all_test.go:301: package execv does not have package comment
    all_test.go:301: package build does not have package comment
    all_test.go:301: package configure does not have package comment
    all_test.go:301: package main does not have package comment
    all_test.go:301: package postprocessor does not have package comment
    all_test.go:301: package protoc does not have package comment